version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rental_crm_db
    environment:
      POSTGRES_DB: rental_crm
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  web:
    build: .
    container_name: rental_crm_web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rental_user:rental_password@postgres:5432/rental_crm
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  bot:
    build: .
    container_name: rental_crm_bot
    command: python bot/main.py
    environment:
      - DATABASE_URL=postgresql://rental_user:rental_password@postgres:5432/rental_crm
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
